#!/bin/zsh
set -u

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd -P)"
ARTIFACT_DIR="$ROOT_DIR/artifacts/m8-001"
RESULT_FILE="$ARTIFACT_DIR/result.txt"

mkdir -p "$ARTIFACT_DIR"
rm -f "$RESULT_FILE"

cd "$ROOT_DIR" || exit 1

swift run M8001ReleaseCandidateAcceptance \
  > "$ARTIFACT_DIR/acceptance.stdout.log" \
  2> "$ARTIFACT_DIR/acceptance.stderr.log"
run_status=$?

if [[ ! -f "$RESULT_FILE" ]]; then
  cat > "$RESULT_FILE" <<'EOF'
BUILD_PASSED=no
SERVICE_INSTALLED=no
SERVICE_STARTED=no
XPC_HANDSHAKE_PASSED=no
REQUEST_SUBMIT_PASSED=no
REQUEST_COMPLETION_PASSED=no
REQUEST_CANCEL_PASSED=no
REQUEST_APPROVAL_PASSED=no
AUTHORIZED_ROOT_PASSED=no
FILE_EVENT_PASSED=no
SYSTEM_EVENT_PASSED=no
EVENT_POLICY_DRY_RUN_PASSED=no
EVENT_POLICY_EXECUTION_PASSED=no
EVENT_POLICY_APPROVAL_PASSED=no
PERMISSIONS_DOCTOR_PASSED=no
AUDIT_INTEGRITY_PASSED=no
AUDIT_SIGNING_PASSED=no
AUDIT_EXPORT_PASSED=no
EMERGENCY_STOP_PASSED=no
RESUME_PASSED=no
UPGRADE_PASSED=no
ROLLBACK_PASSED=no
SBOM_GENERATED=no
CHECKSUMS_GENERATED=no
RELEASE_MANIFEST_GENERATED=no
DEVELOPER_ID_AVAILABLE=no
NOTARIZATION_AVAILABLE=no
CLEAN_UNINSTALL_PASSED=no
RESIDUAL_LAUNCH_AGENT=yes
RESIDUAL_KEYCHAIN_FILE=no
RESIDUAL_PROCESS=yes
PRIVATE_PATH_EXPOSED=no
PROMPT_EXPOSED=no
TOKEN_EXPOSED=no
M8_001_RESULT=FAIL
EOF
fi

exit "$run_status"
